pub const POS_TRAITS: [&str; 13] = [
    "Adventurous",
    "Brave",
    "Charming",
    "Demure",
    "Energetic",
    "Free-spirited",
    "Gritty",
    "Handy",
    "Illuminous",
    "Joyous",
    "Kindhearted",
    "Lucky",
    "Motherly",
];
    
pub const NEG_TRAITS: [&str; 13] = [
    "Apathetic",
    "Brooding",
    "Cocky",
    "Dry",
    "Egotistical",
    "Flaky",
    "Gullible",
    "Hypocritical",
    "Insufferable",
    "Judgemental",
    "Know-it-all",
    "Loud",
    "Manipulative",
];

pub const COLORS: [&str; 12] = [
    "Blonde",
    "Brown",
    "Black",
    "Pink",
    "White",
    "Gray",
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
];